version: '3.4'

services:

  exchange.db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword456"

  exchange.api:
    image: ${DOCKER_REGISTRY-}exchangeapi
    build:
      context: .
      dockerfile: src/Services/Exchange.API/Dockerfile
    depends_on:
      - exchange.db
