version: '3.4'

services:

  seq:
    image: datalust/seq:latest
    container_name: seq
    hostname: seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 5340:80
      - 5341:5341

  exchange.redis:
    image: redis:alpine
    container_name: exchange.redis
    hostname: exchange.redis
    ports:
      - 6379:6379

  exchange.db:
    image: mcr.microsoft.com/mssql/server
    container_name: exchange.db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword456"
    ports:
      - 1433:1433

  exchange.api:
    image: ${DOCKER_REGISTRY-}exchangeapi
    build:
      context: .
      dockerfile: src/Services/Exchange/Exchange.API/Dockerfile
    depends_on:
      - exchange.db
      - seq